#!/usr/bin/env bash
#
#  velincoind The velincoin core server.
#
#
# chkconfig: 345 80 20
# description: velincoind
# processname: velincoind
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/velincoind, see below
if [ -f /etc/sysconfig/velincoind ]; then
        . /etc/sysconfig/velincoind
fi

RETVAL=0

prog=velincoind
# you can override the lockfile via VELINCOIND_LOCKFILE in /etc/sysconfig/velincoind
lockfile=${VELINCOIND_LOCKFILE-/var/lock/subsys/velincoind}

# velincoind defaults to /usr/bin/velincoind, override with VELINCOIND_BIN
velincoind=${VELINCOIND_BIN-/usr/bin/velincoind}

# velincoind opts default to -disablewallet, override with VELINCOIND_OPTS
velincoind_opts=${VELINCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $velincoind $velincoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
