description "Velincoin Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env VELINCOIND_BIN="/usr/bin/velincoind"
env VELINCOIND_USER="velincoin"
env VELINCOIND_GROUP="velincoin"
env VELINCOIND_PIDDIR="/var/run/velincoind"
# upstart can't handle variables constructed with other variables
env VELINCOIND_PIDFILE="/var/run/velincoind/velincoind.pid"
env VELINCOIND_CONFIGFILE="/etc/velincoin/velincoin.conf"
env VELINCOIND_DATADIR="/var/lib/velincoind"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # velincoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$VELINCOIND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run velincoind."
        echo "The setting must appear in $VELINCOIND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Velincoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$VELINCOIND_PIDDIR"
    chmod 0755 "$VELINCOIND_PIDDIR"
    chown $VELINCOIND_USER:$VELINCOIND_GROUP "$VELINCOIND_PIDDIR"
    chown $VELINCOIND_USER:$VELINCOIND_GROUP "$VELINCOIND_CONFIGFILE"
    chmod 0660 "$VELINCOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$VELINCOIND_PIDFILE" \
    --chuid $VELINCOIND_USER:$VELINCOIND_GROUP \
    --exec "$VELINCOIND_BIN" \
    -- \
    -pid="$VELINCOIND_PIDFILE" \
    -conf="$VELINCOIND_CONFIGFILE" \
    -datadir="$VELINCOIND_DATADIR" \
    -disablewallet \
    -daemon

